radondb/radondb-mysql-kubernetes

README.md, README_zh.md
Signed-off-by: molliezhang <molliezhang@yunify.com>
/assign @KID-G @andyli029 @hellojimmywang
=> add readme_zh and modify readme files

README.md, README_zh.md
[summary]
fix some errors adjust some descriptions on README.md and README_zh.md
=> README.md: fix some errors adjust some descriptions #37

PROJECT, config/default/kustomization.yaml, controllers/cluster_controller.go, controllers/suite_test.go, go.mod, main.go
=> *: modify the repo

charts/helm/Chart.yaml, charts/helm/README.md, charts/helm/dockerfiles/mysql/README.md, charts/helm/values.yaml, docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md, docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_appstore.md, docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_repo.md, docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md, docs/zh-cn/charts.md, docs/zh-cn/mysql.md
/enhancement
Fixes #122 
Summary:
update the percona image from 5.7.33 to 5.7.34
=> *: update the percona image from 5.7.33 to 5.7.34

docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md, docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md
doc
Fixes #126 
cd charts  ->  cd charts/helm
=> docs : update the path of helm chart #126

docs/Kubernetes/deploy_radondb-mysql_operator_on_k8s.md
quickstart for radondb mysql operator
Fixes #127
=> docs: quickstart for radondb mysql operator #127

cluster/cluster_test.go, cluster/container/auditlog_test.go, cluster/container/init_mysql_test.go, cluster/container/init_sidecar_test.go, cluster/container/metrics_test.go, cluster/container/mysql_test.go, cluster/container/slowlog_test.go, cluster/container/xenon_test.go, go.mod, go.sum
/enhancement
for #130，unfinished
todo: syncer
```
PASS
coverage: 100.0% of statements
ok      github.com/radondb/radondb-mysql-kubernetes/cluster     0.280s
PASS
coverage: 100.0% of statements
ok      github.com/radondb/radondb-mysql-kubernetes/cluster/container   0.476s
```
=> cluster: unit test for container,cluster #130

sidecar/config.go
=> sidecar: fix root@127.0.0.1 privileges #162

cluster/syncer/statefulset.go, cluster/syncer/status.go
/bug
Fixes #158 
Summary:
1. return error, when check ReadyReplicas condition failure
=> cluster: fix the bug of unchange when the status is't updated. #158

cluster/syncer/statefulset.go
/enhancement
Fixes #165
Summary: add rolling update feature code annotation
=> syncer: add rolling update feature code annotation #165

cluster/syncer/statefulset.go
/bug
Fixes #179
Summary:  change one of slowlog to auditlog.
=> syncer: fix the auditLog container #179

api/v1alpha1/cluster_types.go, config/crd/bases/mysql.radondb.com_clusters.yaml
=> api,config: fix the incorrect description about MetricsOpts

README.md, README_zh.md, docs/Kubernetes/deploy_radondb-mysql_operator_on_k8s.md
/documentation
Fixes #127 
Summary:
1. Modify README for addind the deploy-operator links
2. Modify deploy-operator for fixing .io to .com  
@andyli029 @runkecheng
=> * : Modify README and deploy-operator files #127

.github/workflows/auto_build_operator.yml, .github/workflows/auto_build_sidecar.yml, .github/workflows/greetings.yml
/enhancement
Fixes #134
Summary:
- Automatically update the corresponding images(operator, sidecar) according to the modified file.
- Automatically greet when submitting an issue for the first time.
Also need to add:
- Automatic test when submitting pr
- Automatically add tags to issue/pr
**To make the yml file effective, must set the environment variables first!**
=> *: add ci for images management and greeting.

Dockerfile
/bug
Fixes #208
Summary: .cn image is changed to .io
=> *: .cn image is changed to .io #208

api/v1alpha1/cluster_types.go, cluster/cluster_test.go, cluster/container/backup.go, cluster/container/init_mysql_test.go, cluster/container/init_sidecar.go, cluster/container/init_sidecar_test.go, cluster/container/mysql_test.go, cluster/syncer/metrics_service.go, cluster/syncer/secret.go, cluster/syncer/statefulset.go, internal/sql_runner.go, sidecar/config.go, utils/common.go, utils/constants.go
use command 
```shell
gofumpt --lang=v1.12 -l -w .
```
/format
Fixes #212 
Summary:
=> *: format the code with gofumpt  #212

charts/mysql-operator/templates/cluster_rbac.yaml
=> charts: fix the bug which historyLimit do not work #222

api/v1alpha1/backup_types.go, cluster/syncer/statefulset.go, sidecar/config.go
=> api,cluster,sidecar: fix the bug for infinite loop #201, #219

docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md, docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md, docs/kubesphere/deploy_radondb-mysql_on_kubesphere.md, docs/kubesphere/deploy_radondb-mysql_on_kubesphere_appstore.md, docs/kubesphere/deploy_radondb-mysql_on_kubesphere_repo.md
documentation
Fixes #191 
Summary:
Change the related name of qingcloud to radondb.
Qing@123 --> RadonDB@123
qc_ --> radondb_
qingcloud-->radondb
@acekingke @andyli029 @KID-G @runkecheng
=>  docs *：Modify the default name and password #191

README.md, README_zh.md, docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
/documentation
Fixes #240 
Summary:
- Remove the helm version deployment document link.
- Fix the way to uninstall the operator.
=> *: Remove the helm version deployment document link and fix operator deployment document.

Makefile, go.mod, test/e2e/e2e.go, test/e2e/e2e_test.go, test/e2e/framework/test_context.go
/test
Fixes #199 
Summary:
1. "make e2e-local" without any other env.
2. here we add module "staging" and use "replace" in go.mod in case we
meet error and fix unknown revision v0.0.0 when use go mod tidy.
see: https://github.com/kubernetes/kubernetes/issues/79384
3. the prototype framework is extracted from kubernetes, for more details,
see: https://github.com/kubernetes/kubernetes/tree/master/test/e2e
4. new file:
test/e2e/e2e.go
test/e2e/framework/config/config.go
test/e2e/framework/test_context.go
[test]
test/e2e/e2e_test.go
test/e2e/framework/config/config_test.go
=> test: e2e prototype framework stage 1 #199

docs/mgt_mysqluser.md
/documentation
Fixes #
Summary:
=> docs: fix check CRD about mysqluser.

mysqlcluster/container/init_sidecar_test.go, mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go, mysqlcluster/syncer/metrics_service.go, sidecar/config.go, utils/constants.go
=> Feature fix bug of not effective version of mysql56 #203

Dockerfile
/enhancement
Fixes #287
Summary:
- Dockerfile: Provide backup of district/static:nonroot image. #287
=> Dockerfile: Provide backup of district/static:nonroot image. #287

charts/mysql-operator/templates/deployment.yaml, charts/mysql-operator/values.yaml
/enhancement
Fixes #300 
Summary: `rbacProxy.image` parameter is provided in `values.yaml`.
=> charts: Support to modify the RBAC image of Operator. #300

api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/Chart.yaml, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
/documentation
/enhancement
Fixes #290 #297 
Summary:
- api: Set the default sidecar image tag to latest.
- charts: Update Chart version number and description.
- docs: Update the outdated description.
=> *: Update deployment document and outdated description.

.github/workflows/code_check.yml, .github/workflows/publish_charts.yml
/enhancement
Fixes #290 
Summary: 
- Automatically pack Chart and update to operator-Charts branch. 
- Provide remote Chart warehouse services via Github Page.
To make this CI take effect, need to create branch `operator-charts` and open Page.
test action:
https://github.com/runkecheng/radondb-mysql-kubernetes/actions/runs/1443227755
test branch:
https://github.com/runkecheng/radondb-mysql-kubernetes/tree/helm-charts
=> workflow: Manage Chart using Helm REPO. #290

sidecar/config.go, sidecar/init.go
/enhancement
Fixes #292 
Summary:
=> sidecar: change restore.sh to go codes #292

mysqlcluster/syncer/statefulset.go
/enhancement
Fixes #304 
Summary:
=> mysqlcluster: support replica is 0, but data need to be reserverd #304

mysqlcluster/container/init_sidecar.go, mysqlcluster/container/init_sidecar_test.go, mysqlcluster/syncer/follower_service.go, mysqlcluster/syncer/headless_service.go, mysqlcluster/syncer/leader_service.go, sidecar/config.go, sidecar/init.go, sidecar/server.go, sidecar/util.go
/enhancement
Fixes #250 
Summary:
1. add http download endpoint, use to backup to http stream.
2. when initialize, download backup copies from http stream, and create `restore.sh` script, restore and initialize
=> mysqlcluster,sidecar: support Clone initial when add new pod, and fix   bug after extend pvc, restore from backup fail  #250, #370

mysqlcluster/syncer/statefulset.go
/bug
Fixes #310 
The default PodDisruptionBudget is 50%, so the minimum available node of the 3-node cluster is 2, but in fact, when the configuration is updated, the two nodes will update at once, which does not match the PDB.
root cause: 
The `StatefulSetUpdateStrategy` is `OnDelete`, delete POD by logic as follows，
```
if pod.ObjectMeta.Labels["controller-revision-hash"] == s.sfs.Status.UpdateRevision {
log.Info("pod is already updated", "pod name", pod.Name)
} else {
...
if pod.DeletionTimestamp != nil {
log.Info("pod is being deleted", "pod", pod.Name, "key", s.Unwrap())
} else {
if err := s.cli.Delete(ctx, pod); err != nil {
return err
}
}
}
```
after delete a pod, retry will exit in advance because the health tag of the node being deleted is still `yes`. The correct logic is …
=> syncer: Set the health label to `no` before updating pod. #310

mysqlcluster/syncer/statefulset.go
/bug
Fixes #312 
Summary:
remove preUpdate logic, is useless for current version.
=> syncer: remove preUpdate logic. #312

mysqlcluster/container/mysql.go, mysqlcluster/container/mysql_test.go
/bug
Fixes #305 
Summary:
use `pgrep mysqld` to replace `mysqladmin ping`
=> sysbench press the database, Pod is recreated by k8s #305

sidecar/init.go
/enhancement
Fixes #322 
Summary:
=> sidecar:  first choose follower to clone init #322

charts/mysql-operator/values.yaml, config/default/manager_auth_proxy_patch.yaml
/enhancement
Fixes #146 
Summary: 
gcr.azk8s.cn/kubebuilder -> radondb(dockerhub)
=> charts: change the default path of the rbac proxy image. #146

api/v1alpha1/backup_types.go, api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/crds/mysql.radondb.com_backups.yaml, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, charts/mysql-operator/values.yaml, config/crd/bases/mysql.radondb.com_backups.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, config/samples/mysql_v1alpha1_backup.yaml, config/samples/mysql_v1alpha1_mysqlcluster.yaml, docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
/bug
/documentation
Fixes #351
Summary:
- change the default tag to v2.1.0.
- update the doc.
=> *: Change the default tag to v2.1.0. 

docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md
/documentation
Fixes #
Summary:
In order to ensure the consistency of the Helm repo and Release, the example YAML should also be downloaded from Release.
=> doc: Download the latest stable version of YAML from Release.

.gitignore, test/e2e/simplecase/list_namespace.go
1. Add .gitignore about test/e2e/logs_*
2. Modify the list_namespace.go
Fixes #
Summary:
=> *: fix .gitignore about e2e logs and function

hack/xenon/Dockerfile
/enhancement
Fixes #336 
Summary: XENON_BRANCH：feature_adapt_k8s -> master
=> hack: Change Xenon's Dockerfile image branch to master. #336

docs/en-us/DebugMode.md, mysqlcluster/container/mysql.go, mysqlcluster/container/mysql_test.go
/enhancement
Fixes #375 
Summary:
add the debug mode, make container never recreate when mysqld crashed
=> mysqlcluster: Debug Mode for Pod #375

mysqlcluster/container/xenon.go, mysqlcluster/container/xenon_test.go
/bug
Fixes #404 
Summary: Add xenoncli check in the liveness probe.
=> container: Add xenoncli check in the liveness probe.  

docs/zh-cn/deploy_radondb-mysql_operator_on_k8s_offline.md
doc
Fixes #396 
Summary:
- Provide deployment resource compression package `radondb-mysql-resources.tar.gz` in Release.
- Tutorial for offline deployment 
The resources needed to deploy have been uploaded to Release.
Need to verify that the process can go through.
=> docs: Add offline deployment document. #396

docs/troubleshoot/zh-cn/troubleshoot.md
=> docs: add troubleshoot.md #387

docs/en-us/rebuild.md, mysqlcluster/syncer/status.go, utils/constants.go
/enhancement
Fixes #385 
Summary:
1. track lable `rebuild` and rebuild the pod
=> mysqlcluster: Support automatic rebuild of nodes by label.

charts/mysql-operator/Chart.yaml
=> chart: update chart version to v2.1.3.

cmd/sidecar/main.go
/bug
Summary: If you use unbuffered channel, it is possible to lose the signal.
Fixes: https://github.com/radondb/radondb-mysql-kubernetes/issues/412
=> cmd: Change HttpServer stop channel to buffered channel. #411

.github/release-drafter.yml, .github/workflows/build_operator_image.yml, .github/workflows/build_sidecar_image.yml, .github/workflows/code_check.yml, .github/workflows/greetings.yml, .github/workflows/publish_charts.yml, .github/workflows/publish_images.yml, .github/workflows/publish_release.yml, .github/workflows/release_drafter.yml, .github/workflows/unit_tests.yml
/enhancement
Fixes #421
Summary:  
- [Automatic create Release](https://github.com/runkecheng/radondb-mysql-kubernetes/releases)
- Automatic generate Release Log
- Automatic update images
- Automatic update Chart version
- Automatic update Operator default version
- [Automatic update Chart remote repo](https://github.com/runkecheng/radondb-mysql-kubernetes/tree/operator-charts)
- Set the label to the PR (the label will determine how to increase the version number.)
- Click git action `Publish release`
=> workflow: Publish release only one click. #421

.github/release-drafter.yml
=> .github: adjust release-drafter

docs/en-us/deploy_backup_restore_s3.md, docs/zh-cn/deploy_backup_restore_s3.md
=> docs: fix typo

docs/en-us/deploy_radondb-mysql_operator_on_k8s.md, docs/en-us/deploy_radondb-mysql_operator_on_rancher.md
Signed-off-by: Patrick-LuoYu <patrickluo@yunify.com>
/documentation
/assign @KID-G
=> docs: Translate 'deploy_radondb-mysql_operator_on_k8s.md' and 'deploy_radondb-mysql_operator_on_rancher.md'

.github/workflows/code_check.yml
/bug
Fixes #431 
Summary: [workflow: Specify version of staticcheck.](https://github.com/radondb/radondb-mysql-kubernetes/commit/9aff314479b45010335cce2ea24e13591d84ecad) https://github.com/radondb/radondb-mysql-kubernetes/issues/431
=> workflow: Specify version of staticcheck. #431

docs/en-us/build_images_and_apply.md
/doc
Fixes #409 
Summary: Add tutorial of building images.
=> docs: Add tutorial of building images. #409

charts/mysql-operator/templates/deployment.yaml, charts/mysql-operator/values.yaml
/enhancement
Fixes #415 
Summary:
- update chart version to 0.1.2.(we can update helm repo using ci)
- provide a parameter `tolerationSeconds` in values.yaml
=> Chart: optimize operator availability

Makefile, config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml, docs/en-us/deploy_radondb_mysql8.md, mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_mysql_test.go, mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go, mysqlcluster/syncer/config_map.go, mysqlcluster/syncer/statefulset.go, mysqlcluster/syncer/variables.go, sidecar/config.go, sidecar/init.go, utils/constants.go
/enhancement
Fixes #176 
Summary:
support mysql8
=> cluster,config,sidecar,utils: support the MySQL8.0 #176

Makefile, api/v1alpha1/backup_types.go, api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/crds/mysql.radondb.com_backups.yaml, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, charts/mysql-operator/values.yaml, config/crd/bases/mysql.radondb.com_backups.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, config/samples/mysql_v1alpha1_mysqlcluster.yaml, config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml, config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml, docs/en-us/deploy_radondb_mysql8.md, mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_mysql_test.go, mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go, mysqlcluster/syncer/config_map.go, mysqlcluster/syncer/mysql_configs.go, mysqlcluster/syncer/statefulset.go, mysqlcluster/syncer/variables.go, sidecar/config.go, sidecar/init.go, utils/constants.go
=> Support MySQL 8.0

sidecar/config.go, sidecar/init.go
/bug
Fixes #450
Summary: Skip reset slave all when initialization.
=> sidecar: Skip `reset slave all` when initialization.

.github/workflows/build_sidecar_image.yml, .github/workflows/release_drafter.yml
/enhancement
Fixes #
Summary:
- support upload release assets.
- support build mysql8 images.
action: https://github.com/runkecheng/radondb-mysql-kubernetes/actions/runs/2166689383
release: https://github.com/runkecheng/radondb-mysql-kubernetes/releases/tag/v3.0.1
=> workflow: support mysql8.0.

config/samples/backup_secret.yaml
=> config: fix bug about apiVersion #148

.github/workflows/publish_release.yml, .github/workflows/release_drafter.yml
/enhancement
Fixes #
ref: #421
Summary: 
- If the version is inputted, use the input version to publish release.
- If input is empty(default), follow the original logic, automatically increment the version number.
=> ci: Support custom release version.

sidecar/config.go
=> mysqlcluster: Support ipv6 address. #441

sidecar/config.go
=> mysqlcluster, sidecar: Support ipv6 address. #441

api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
/enhancement
Fixes #476
Summary:
New columns: SpecReplicas, ReadyNodes, Leader
```
$ kubectl get mysql sample
before:
NAME     READY     REPLICAS       AGE
sample   true      3              27h
after:
NAME     STATE     DESIRED         CURRENT        LEADER                                AGE
sample   Ready      3              3              sample-mysql-0.sample-mysql.default   27h
```
=> crd: Add more `additionalPrinterColumns`. #476

go.mod, go.sum, mysqlcluster/mysqlcluster_test.go
/enhancement
Fixes #483
Summary: `bou.ke/monkey` -> `github.com/agiledragon/gomonkey/v2`
=> mysqlcluster: Use gomonkey instead of Monkey. #483

README.md, README_zh.md
/documentation
Fixes #
Summary:
Update README.md's Style
=> Docs: Update README.md

backup/backup.go, backup/status.go, backup/syncer/job.go, mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go, mysqlcluster/syncer/mysql_cm.go, mysqlcluster/syncer/mysql_configs.go, mysqlcluster/syncer/statefulset.go, mysqlcluster/syncer/status.go
/bug
Fixes #469
Summary:
1. fix the `log` memleaks.
=> *: Fix memory Leak of Operator. #469

api/v1alpha1/backup_types.go, api/v1alpha1/mysqlcluster_types.go, api/v1alpha1/mysqlcluster_webhook.go, charts/mysql-operator/crds/mysql.radondb.com_backups.yaml, config/crd/bases/mysql.radondb.com_backups.yaml, config/samples/mysql_v1alpha1_backup.yaml, docs/en-us/deploy_backup_restore_s3.md, docs/zh-cn/deploy_backup_restore_s3.md
=> *: fix typo and comments #494

README.md
=> README: fix error about link. #496

mysqlcluster/syncer/status.go
/bug
Fixes #
Summary:
Mergefrom() needs to use the old object.
=> syncer: failed to patch pod labels.

controllers/mysqlcluster_controller.go
/bug
Fixes #464 
Summary:
when the cluster is deleted, do not need update the status.
=> controller: operator crash #464

mysqlcluster/syncer/mysql_cm.go
/enhancement
Fixes #523
Summary:
1. Remove the duplicate configuration parameters in mysql cm.
2. Support update the mysql plugin configuration.
=> syncer: Support update the mysql plugin configuration.

charts/mysql-operator/templates/deployment.yaml
=> fix(chart): syntax error

mysqlcluster/syncer/mysql_cm.go
=> fix(syncer): failed to update my.cnf

mysqlcluster/syncer/statefulset.go
/revert
Fixes #
Summary: fix logic of updating sts first
=> revert(cluster): actively switch leader to updated pod.

mysqlcluster/syncer/status.go
/bug
Fixes #534 
Summary:
1. update all pods , not only ready nodes.
=> mysqlcluster: fix the error for pod's label no change #534

mysqlcluster/syncer/statefulset.go
/bug
Fixes #532
Summary:
only when ` sts.spec.template` is updated will trigger roll update
=> fix(cluster): Rolling update trigger logic incorrect.

mysqlcluster/container/backup.go, mysqlcluster/container/mysql.go, mysqlcluster/container/mysql_test.go, mysqlcluster/container/xenon.go, mysqlcluster/container/xenon_test.go
=> container: adjust readiness timeout #542

sidecar/init.go
=> sidecar:prevent useless clone data when booting sidecar

internal/sql_runner.go, mysqlcluster/syncer/statefulset.go, mysqlcluster/syncer/status.go
/bug
Fixes #
Summary:
add a check for the unfinished update
add timeout for get sqlrunner
=> fix(cluster): add a check for the unfinished update

mysqlcluster/syncer/mysql_cm.go
/bug
Fixes #562 
Summary:
1. replace old items, and append new items.
=> mysqlcluster: fix the bug for replace config items #562

mysqlcluster/syncer/statefulset.go, mysqlcluster/syncer/statefulset_test.go
/bug
Fixes #
Summary:
add support for resizing volume
add unit test for sfsUpdated()
=> fix(cluster): failed to update volume size.

mysqlcluster/syncer/mysql_cm.go
=> fix(cluster): configmap abnormal update

Dockerfile, Dockerfile.sidecar
=> dockerfile: Remove GOPROXY settings  in dockerfile

controllers/backup_controller.go, mysqlcluster/syncer/statefulset.go
=> controllers,mysqlcluster: fix the backup Running bug#572

charts/mysql-operator/Chart.yaml, config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
=> release v2.2.0

mysqlcluster/syncer/role.go
=> mysqlcluster: remove error role policy rule

internal/sql_runner.go
/enhancement
Fixes #
link #175 
support changing passwords.
> Notice: hosts can not be update with cr.
Summary:
=> internal: support changing passwords.

cmd/xenon/main.go
=> xenon: runCommandLocal timeout kill

build/xenon/Dockerfile
=> dockerfile: set go proxy though localtimezone

controllers/mysqluser_controller.go, internal/sql_runner.go, mysqlcluster/container/auditlog.go, mysqlcluster/container/backup.go, mysqlcluster/container/container.go, mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_sidecar.go, mysqlcluster/container/metrics.go, mysqlcluster/container/mysql.go, mysqlcluster/container/mysql_test.go, mysqlcluster/container/slowlog.go, mysqlcluster/container/xenon.go, mysqlcluster/syncer/secret.go, mysqlcluster/syncer/status.go, sidecar/config.go, sidecar/init.go, sidecar/util.go
Fixes #
Summary:
- feat(cluster): remove init.sql after mysql started
- feat(cluster): correct the scope of user host
- feat(cluster): add args in mysqld init command
=> *: improve security

Dockerfile, Dockerfile.sidecar, Makefile, build/mysql/Dockerfile, build/mysql/encypt.sh, build/xenon/Dockerfile, mysqlcluster/syncer/mysql_configs.go, mysqlcluster/syncer/secret.go, mysqlcluster/syncer/secret_test.go, sidecar/config.go, sidecar/init.go
=> *: add validate password

Dockerfile.sidecar, build/xenon/Dockerfile, charts/helm/templates/secrets.yaml, cmd/xenon/main.go, internal/xenon_request.go, mysqlcluster/container/mysql.go, mysqlcluster/syncer/mysql_configs.go, sidecar/config.go, utils/constants.go
=> *: rename root to super for security

mysqlcluster/container/container.go
…il #626
/bug
Fixes #626 
Summary:
1. add shell script ,after first start, delete the `reset slave all`
=> mysqlcluser,sidecar: fix restart mysql container cause replication fail

test/e2e/README.md, test/e2e/cluster/cluster.go, test/e2e/e2e_test.go, test/e2e/framework/cluster_util.go, test/e2e/framework/framework.go, test/e2e/framework/helm.go, test/e2e/framework/test_context.go
/documentation
/enhancement
Fixes #344 
Summary:
- mysqlcluster related api.
- test cases of scaling cluster.
=> e2e: cluster related api and test case. #344

docs/zh-cn/mgt_mysqluser.md
/documentation
Fixes #
Summary:
English @hayleyling 
Require test @qianfen2021
=> doc: Add parameter introduction and connection tutorial

api/v1alpha1/backup_types.go, api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/Chart.yaml, charts/mysql-operator/crds/mysql.radondb.com_backups.yaml, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, charts/mysql-operator/values.yaml, config/crd/bases/mysql.radondb.com_backups.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, config/manager/kustomization.yaml, config/samples/mysql_v1alpha1_backup.yaml, config/samples/mysql_v1alpha1_mysqlcluster.yaml, config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml, config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml, config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml, test/e2e/README.md, test/e2e/framework/test_context.go
Fixes #
Summary: release v2.2.1
update the default version
=> release v2.2.1

api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, config/samples/mysql_v1alpha1_mysqlcluster.yaml, config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml, config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml, config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml, docs/en-us/config_para.md, docs/zh-cn/config_para.md
=> *: update the default tag of xenon

controllers/backup_controller.go
/bug
Fixes #664
Summary:
1. fix the bug for auto backup's missing label.
=> controller: fix the bug missing label of recurrent #664

README.md, README_zh.md
/documentation
Fixes #
Summary:
Readme add Repobeat part from [https://repobeats.axiom.co/](https://repobeats.axiom.co/)
=> README: Add Repobeats Part

config/samples/nfs_server.yaml, mysqlcluster/syncer/role.go, mysqlcluster/syncer/status.go, sidecar/init.go, utils/constants.go
/bug
Fixes #652 
Summary:
1. use number such as 0, 1 ,2 etc to rebuild lable value， which indicate the pod ord in statefulset.
=> *: rebuild from special pod #652

api/v1alpha1/backup_types.go, backup/syncer/job.go, charts/mysql-operator/crds/mysql.radondb.com_backups.yaml, config/crd/bases/mysql.radondb.com_backups.yaml
/enhancement
Fixes #668
Summary:
1. add column for backup which indicate Success.
=> api,backup: add printcolumn for Success #668

Makefile, backup/syncer/job.go
/enhancement
Fixes #663
Summary:
=> *: add disk usage check in nfs backup #663

sidecar/config.go, sidecar/init.go, sidecar/util.go
/bug
Fixes #691
Summary:
restore from /var/lib/mysql execpt nfs restore.
=> sidecar: remove xtrabackup copy back #691

api/v1alpha1/mysqlcluster_types.go, charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, controllers/mysqlcluster_controller.go, mysqlcluster/container/xenon.go, mysqlcluster/container/xenon_test.go
/enhancement
Fixes #361
Summary:
when single node, do not use xenon container.
=> *: Support running single node. #361

test/e2e/framework/sysbench.go, test/e2e/install/cleanup.go, test/e2e/install/cluster.go, test/e2e/install/cluster_asset.go
=> feat(e2e): support sysbench

.gitignore, Dockerfile, api/v1alpha1/mysqlcluster_webhook.go
=> api: validate mysql image and mysqlversion on cluster create

mysqlcluster/container/auditlog.go, mysqlcluster/container/auditlog_test.go, mysqlcluster/container/slowlog.go, mysqlcluster/container/slowlog_test.go
=> mysqlcluster: fix failed to start pod for first time #545

charts/mysql-operator/templates/mysql80_template.yaml
=> chart: radondb-mysql80-template cannot use mysql5 config #720

Dockerfile.sidecar, backup/syncer/job.go
/bug
Fixes #725 
Summary:
expr command compare float number uncorrect, use `bc` instead.
=> *: replace expr commond to bc #725

mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go
=> mysqlcluster: Fix image namespace override

charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml, docs/en-us/backup_cron.md, docs/zh-cn/backup_cron.md
/documentation
Fixes #735
Summary:
1.  add documents and missing charts.
=> doc,chart: add the both s3 nfs backup documents #735

controllers/backupcron_controller.go
/bug
Fixes #737 
Summary:
1. fix the auto backup with boths3 nfs
=> controllers: fix the bug for auto backup #737

controllers/backupcron_controller.go
=> controller: fix the auto backup nfs error #740

sidecar/init.go
=> sidecar: fix #770 change owener of plugin and xtraconf

cmd/sidecar/main.go
/enhancement
Fixes #778 
add  log fmt in init-sidecar and backup container.
Summary:
=> cmd: add log fmt  in sidecar

sidecar/init.go
=> sidecar: fix #770 change owener of plugin and xtraconf (#771)

controllers/backup/backup_controller.go
=> backup:fix s3 backup empty env

api/v1beta1/zz_generated.conversion.go, controllers/backup/backup_controller.go
=> Only when backup is going, rollingup updating should pause #790

api/v1beta1/mysqlcluster_conversion.go
=> api:crash backup convert in operetor. #796

mysqlcluster/syncer/status.go
=> fix the bug about xenon check

charts/mysql-operator/templates/mysql.radondb.com_backups.yaml, charts/mysql-operator/templates/mysql.radondb.com_mysqlclusters.yaml
Fixes #
helm install namesapce  is always default.
Summary:
=> charts: add crd convert namespaces

controllers/mysqlcluster_controller.go, utils/constants.go
/enhancement
Fixes # add maintain mode
Summary:
=> *: add maintain mode, for delete leader svc

api/v1alpha1/mysqlcluster_types.go, api/v1beta1/mysqlcluster_conversion.go, api/v1beta1/mysqlcluster_types.go, charts/mysql-operator/templates/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, mysqlcluster/container/container.go, mysqlcluster/container/errorlog.go, mysqlcluster/mysqlcluster.go, mysqlcluster/syncer/statefulset.go, utils/constants.go
Fixes # add error log to file
Summary:
=> *: add errorlog to file

api/v1beta1/mysqlcluster_conversion.go
=> api: add storageclass in convertsation

mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_mysql_test.go, mysqlcluster/container/init_sidecar.go, mysqlcluster/container/init_sidecar_test.go, mysqlcluster/syncer/mysql_cm.go, mysqlcluster/syncer/secret.go, mysqlcluster/syncer/status.go, sidecar/config.go, sidecar/init.go, utils/constants.go
/enhancement
Fixes #808 
Summary:
=> *: add clone for mysql 8 #808

api/v1alpha1/mysqlcluster_webhook.go, api/v1alpha1/webhook_suite_test.go, cmd/xenon/main.go, mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_mysql_test.go, mysqlcluster/container/init_sidecar.go, mysqlcluster/mysqlcluster.go, mysqlcluster/mysqlcluster_test.go, mysqlcluster/syncer/statefulset.go, sidecar/config.go, sidecar/init.go
/enhancement
Fixes # upgrade mysql8.0.19~8.0.25~8.0.33
Summary:
=> *: add mysql8.0.19~33 upgrade

charts/mysql-operator/templates/crds.yaml
=> chart: fix the bug installcrds #816

api/v1alpha1/mysqlcluster_types.go, api/v1beta1/mysqlcluster_types.go, api/v1beta1/zz_generated.conversion.go, charts/mysql-operator/templates/mysql.radondb.com_mysqlclusters.yaml, config/crd/bases/mysql.radondb.com_mysqlclusters.yaml, mysqlcluster/syncer/follower_service.go
/enhancement
Fixes # add the leader node to follower 
Summary:
=> *: add leader to follower choice

controllers/mysqluser_controller.go, internal/sql_runner.go
Fixes # create user bug
Summary:
=> *: fix the bug of create user

Dockerfile, Dockerfile.sidecar-arm64, build/xenon/Dockerfile.arm64, build_mutiplatform.sh
Fixes #
Summary:
add arm64 build scripts and dockerfile
=> *: add build arm64 dockerfile and shell script

mysqlcluster/container/backup.go, mysqlcluster/container/container.go, mysqlcluster/container/metrics.go, mysqlcluster/container/metrics_test.go, mysqlcluster/container/mysql.go, mysqlcluster/container/mysql_test.go, mysqlcluster/container/xenon.go, mysqlcluster/container/xenon_test.go
/enhancement
Fixes # change timeout values.
Summary:
change timeout values.
=> *: change timeout values

Dockerfile57.sidecar, Dockerfile57.sidecar-arm64, Dockerfile80.sidecar, Dockerfile80.sidecar-arm64, Makefile, build_mutiplatform.sh, controllers/backup/backup_controller.go, controllers/backupcron_controller.go, mysqlcluster/container/init_mysql.go, mysqlcluster/container/init_mysql_test.go, mysqlcluster/container/xenon.go, mysqlcluster/container/xenon_test.go, mysqlcluster/syncer/mysql_cm.go, mysqlcluster/syncer/mysql_configs.go, sidecar/config.go, sidecar/init.go
/bug
Fixes # remove the connection plugin, and change the scripts, and so on.
Summary:
=> *: add Optimise about parameters and scripts

charts/mysql-operator/Chart.yaml, charts/mysql-operator/values.yaml
=> change version tag of charts
