radondb/radondb-mysql-kubernetes

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general-question.md
.github/ISSUE_TEMPLATE/support-request.yml
.github/PULL_REQUEST_TEMPLATE.md

/enhancement
Fixes #90 
Summary:
Refer to [the github article](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), add pull request and issue templates for radondb-mysql-kubernetes.
We can customize and standardize the information we'd like contributors to include when they open issues and pull requests in radondb-mysql-kubernetes.
N/A

.github: add pull request and issue templates #90

---

README.md
README_zh.md

add links 
- [Deploy RadonDB MySQL through git on Kubesphere](docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md)
- [Deploy RadonDB MySQL through helm repo on Kubesphere](docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_repo.md)
- [Deploy RadonDB MySQL through Appstore of KubeSphere](docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_appstore.md)

add deploy links on README.md and README_zh.md #51

---

charts/helm/dockerfiles/mysql/Dockerfile
charts/helm/dockerfiles/mysql/mysql-entry.sh

/enhancement
Fixes #122 
Summary:
Update percona version to 5.7.34.
Add init file operator.
https://www.percona.com/doc/percona-server/5.7/installation/apt_repo.html#installing-percona-server-from-percona-apt-repository

dockerfiles/mysql: update mysql version to 5.7.34 and add init operator

---

charts/helm/Chart.yaml
charts/helm/README.md
charts/helm/dockerfiles/mysql/README.md
charts/helm/dockerfiles/xenon/README.md
charts/helm/values.yaml
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_appstore.md
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_repo.md
docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md
docs/zh-cn/charts.md
docs/zh-cn/mysql.md
docs/zh-cn/xenon.md

documentation
enhancement
Fixes #140
Summary: 
- move images(percona,xenon) to radondb repository
- change the key word : xenondb -> radondb
- add image radondb/sidecar:v01   **todo**
Test:
after move, Re-deployment, no abnormalities
check again：
```
helm install demo radondb-mysql-kubernetes/charts/helm
```

charts: Move the images and change the key word #140

---

utils/unsafe.go
utils/unsafe_test.go

[summary]
Fix possible misuse of reflect.SliceHeader vet error when go 1.16.6
[test case]
utils/unsafe_test.go
[patch codecov]
utils/unsafe.go 100%
Fixes #139
Summary:

utils: Fix possible misuse of reflect.SliceHeader vet error when go 1.16.6 #139

---

cluster/syncer/statefulset.go

cluster: fix the bug change yaml will happen nothing #158

---

api/v1alpha1/cluster_types.go
charts/helm/README.md
charts/mysql-operator/crds/mysql.radondb.com_clusters.yaml
charts/mysql-operator/values.yaml
config/crd/bases/mysql.radondb.com_clusters.yaml
config/samples/mysql_v1alpha1_cluster.yaml
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere.md
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_appstore.md
docs/KubeSphere/deploy_radondb-mysql_on_kubesphere_repo.md
docs/Kubernetes/deploy_radondb-mysql_on_kubernetes.md
docs/Kubernetes/deploy_radondb-mysql_operator_on_k8s.md
docs/zh-cn/charts.md

*.: fix docker path to radondb #147

---

charts/helm/values.yaml

/enhancement
Fixes #172
Summary: 
xenon image tag of helm version:
radondb/xenon:1.1.5-alpha -> radondb/xenon:1.1.5-helm
https://hub.docker.com/repository/docker/radondb/xenon

charts: change xenon tag of helm version #172

---

cluster/syncer/statefulset.go

/bug
Fixes #184 
Summary:
change the `status.replicas` to `Spec.replicas`

cluster: fix the bug for preUpdate #184

---

cluster/syncer/statefulset.go
cluster/syncer/status.go
utils/common.go
utils/constants.go

/bug
Fixes #178 
Summary:
1. Use the status varibale updating, if preUpdate, set it to be true, if completed, set it to be false

api,cluster: fix the bug for status reset leader #178

---

charts/mysql-operator/templates/_helpers.tpl
charts/mysql-operator/templates/servicemonitor.yaml
charts/mysql-operator/values.yaml
cluster/cluster.go
cluster/syncer/metrics_service.go
controllers/cluster_controller.go
utils/constants.go

/enhancement
Fixes #169
Summary: 
- install servicemonitor when install operator.
- create metrics service when metrics enable
For testing, please set the manager image in `charts/mysql-operator/values.yaml` to `runkecheng/mysql-operator` and set `config/samples/mysql_v1alpha1_cluster.yaml` : 
```
metricsOpts:
enabled: true
``` 
If you are using qke, you can configure port forwarding for the `prometheus-k8s` service which under `kubesphere-monitoring-system` ns, and then you can access prometheus through the external network and view related data interfaces.

*: add serviceMonitor for operator #169

---

cluster/cluster_test.go
cluster/container/init_mysql_test.go
cluster/container/init_sidecar_test.go
cluster/container/mysql_test.go
utils/constants.go

*.: fix default mysql version 5.7.33 to 5.7.34

---

api/v1alpha1/cluster_types.go
backup/syncer/job.go
charts/helm/templates/secrets.yaml
charts/helm/values.yaml
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
charts/mysql-operator/crds/mysql.radondb.com_clusters.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_clusters.yaml
config/samples/mysql_v1alpha1_cluster.yaml
controllers/backup_controller.go
utils/constants.go

/enhancement
Fixes #226 
Summary:

*: simplify backup code #226

---

cluster/cluster.go
cluster/syncer/statefulset.go
cluster/syncer/status.go
cmd/manager/main.go
controllers/cluster_controller.go
controllers/status_controller.go
internal/query.go
internal/sql_runner.go
utils/constants.go

Optimize the logic of creating sqlrunner.
Fixes #229
Summary: Apply the necessary configuration to SQLRunnerFactory to create the corresponding sqlrunner, which simplifies the creation process of sqlrunner.

*: Optimize the logic of creating sqlrunner. #229

---

controllers/backup_controller.go

/bug
Fixes #237 
Summary:
bug reason:
When backup job created ,but need  updatestatus in next reconcile
before clearHistory, the job has completed, it will delete job, 
So it will recreate again when next reconcile.
fix:
when delete the job, check backup status is completed first.

controller: fix the 8 backupJob but create 11 copies #237

---

Makefile

/enhancement
Fixes #279 
Summary:
Added a new `update-crd` method in Makefile，It is used to synchronize the generated YAML files to operator Chart after make manifests.

Makefile: Synchronize the generated files to Chart while generating CRD.

---

mysqlcluster/syncer/status.go

/bug
Fixes #283 
Summary:
Let Nodes.Conitions only contains the conition of the node present in the cluster.

status: Nodes.Conitions only contains the conition of the node present in the cluster. #283

---

api/v1alpha1/mysqlcluster_types.go
internal/xenon_executor.go
mysqlcluster/container/backup.go
mysqlcluster/container/init_sidecar.go
mysqlcluster/container/init_sidecar_test.go
mysqlcluster/container/xenon.go
mysqlcluster/container/xenon_test.go
mysqlcluster/syncer/status.go
sidecar/config.go
sidecar/init.go
utils/common.go
utils/constants.go

/bug
/enhancement
Fixes #221 
Summary: Before the state is set to ready, check raft status and synchronize raft according to the spec.replicas.

*：update replicas without restart

---

mysqlcluster/syncer/statefulset.go

/bug
Fixes #320 
If only `replicas` changes, StatefulSet does not generate new `Revison` , so the `UpdatedReplicas` has always been 0.
```
status:
collisionCount: 0
currentRevision: sample-mysql-55677794
observedGeneration: 6
replicas: 0
updateRevision: sample-mysql-55677794
```
Summary: Use the revision to determine if the POD needs to be updated.

syncer: Optimize update POD trigger conditions

---

docs/rebuild.md
hack/rebuild.sh

docs,hack: support manual repair the Invalid Pod #331

---

docs/kubernetes/deploy_radondb-mysql_on_kubernetes.md
docs/kubernetes/deploy_radondb-mysql_operator_on_k8s.md

/documentation
/enhancement
Fixes #340 
Summary:
@acekingke @andyli029 @runkecheng @qianfen2021 @KID-G

 docs/kubernetes *: Update the description about access radondb mysql #340

---

mysqlcluster/syncer/follower_service.go
mysqlcluster/syncer/leader_service.go
mysqlcluster/syncer/statefulset.go
mysqlcluster/syncer/status.go
sidecar/config.go
sidecar/init.go
sidecar/util.go

/enhancement
Fixes #330 
execute `xenoncli raft disable` in leader `sample-mysql-2`. then `sample-mysql-2` become `IDLE`, Cluster re-electing.
```
xenoncli cluster status
+------------------------------------------+-------------------------------+--------+---------+--------------------------+---------------------+----------------+------------------------------------------+
|                    ID                    |             Raft              | Mysqld | Monitor |          Backup          |        Mysql        | IO/SQL_RUNNING |                 MyLeader                 |
+------------------------------------------+-------------------------------+--------+---------+--------------------------+---------------------+----------------+------------------------------------------+
| …
```

*: Support more role labels.

---

sidecar/config.go

/bug
Fixes #368 
Summary:
Fix it:
add `reset slave all ` in init.sql
When the pod restart all ， slave info will not useful， clear it.

sidecar: sacle 2 to 3 ,mysql-operator restart #368

---

backup/syncer/job.go
charts/mysql-operator/templates/deployment.yaml
charts/mysql-operator/values.yaml
mysqlcluster/container/auditlog_test.go
mysqlcluster/container/container.go
mysqlcluster/container/init_mysql_test.go
mysqlcluster/container/init_sidecar_test.go
mysqlcluster/container/metrics_test.go
mysqlcluster/container/mysql_test.go
mysqlcluster/container/slowlog_test.go
mysqlcluster/container/xenon_test.go
mysqlcluster/mysqlcluster.go
mysqlcluster/mysqlcluster_test.go

feature
Fixes #378
Summary:
- Add parameter `imagePrefix` in Chart
- Add Environment Variable `IMAGE_PREFIX` in the Deployment of Operator
- Automatically add prefix for all images

*: Support custom repository address of images. #378

---

mysqlcluster/syncer/statefulset.go

/enhancement
Fixes #
Summary: 
- Judging whether the node is Leader when scrolling is updated
- When initializing the node, the default status of the node is set to `CANDIDATE`.（In order to maintain a unified）

syncer: Uniform use of global variables set role labels.

---

docs/zh-cn/deploy_radondb-mysql_operator_on_k8s.md
docs/zh-cn/deploy_radondb-mysql_operator_on_rancher.md

/documentation
Fixes #401 
Summary:

docs：Add a description of `service_name` connection method #401

---

config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml

/documentation
/enhancement
ref: #371 
Summary:
Add podAntiAffinity to default sample yaml. 
Guarantee to schedule nodes to different physical machines

config: Add podAntiAffinity to default sample yaml. #371

---

mysqlcluster/syncer/status.go
utils/constants.go

/bug
Fixes #417
Summary:
- Do not return err when operator cannot connect to node.
- Provide a default status which is used to unavailable node.
for test: 
```
helm upgrade demo radondb/mysql-operator --install --set manager.image=runkecheng/mysql-operator --set manager.tag=t0317b
```

status: Skip the unavailable node and set default node status. #417

---

mysqlcluster/container/backup.go
mysqlcluster/container/init_mysql.go
mysqlcluster/container/init_mysql_test.go
mysqlcluster/container/init_sidecar.go
mysqlcluster/container/init_sidecar_test.go
mysqlcluster/container/mysql.go
mysqlcluster/container/mysql_test.go
mysqlcluster/container/xenon.go
mysqlcluster/container/xenon_test.go
sidecar/init.go
sidecar/util.go
utils/constants.go

/enhancement
Fixes #406
Summary:
MySQL and Xenon mount the same volume but use different subpath.
```
containers:
- name: mysql
volumeMounts:
mountPath: /var/lib/mysql
subPath: mysql
...
- name: xenon
volumeMounts:
mountPath: /var/lib/xenon
subPath: xenon
```
Xenon cannot see MySQL dir.
```
kubectl exec -it sample-mysql-0 -c xenon -- ls /var/lib/
apk     misc    udhcpd  xenon
```
MySQL cannot see Xenon dir.
```
kubectl exec -it sample-mysql-0 -c mysql -- ls /var/lib/
alternatives  dnf        misc         mysql-keyring  rpm        systemd
dbus          games      mysql        portables      rpm-state
dhclient      initramfs  mysql-files  private        selinux
```

*: Save Xenon's metadata to persistent storage. #406

---

mysqlcluster/syncer/headless_service.go

fix the bug for headless svc 
/bug
Fixes #433 
Summary:

mysqlcluser: headless svc has other cluster pods #433

---

api/v1alpha1/mysqlcluster_types.go
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
charts/mysql-operator/values.yaml
config/samples/mysql_v1alpha1_mysqlcluster.yaml
config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
mysqlcluster/syncer/config_map.go
mysqlcluster/syncer/mysql_configs.go
sidecar/init.go
utils/constants.go

/enhancement
Fixes #
Summary:
- Set the default value of InitTokuDB to false.
- Separate the configuration of mysql57 and mysql80, remove partially discarded parameters.
- Package the logic of applying configuration to improve code readability.
Some parameters of MySQL57 have been discarded in mysql8.
```
// MySQL init process in progress...
// 2022-04-06T17:05:40.140140+08:00 0 [Warning] [MY-011069] [Server] The syntax '--master-info-repository' is deprecated and will be removed in a future release.
// 2022-04-06T17:05:40.140167+08:00 0 [Warning] [MY-011069] [Server] The syntax '--relay-log-info-repository' is deprecated and will be removed in a future release.
// 2022-04-06T17:05:40.140195+08:00 0 [Warning] [MY-011068] [Server] The syntax 'expire-logs-days' is deprecated and will be …
```

*: Optimize mysql8 related logic.

---

api/v1alpha1/backup_types.go
api/v1alpha1/mysqlcluster_types.go
backup/backup.go
backup/syncer/job.go
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
config/samples/backup_secret.yaml
config/samples/mysql_v1alpha1_backup.yaml
config/samples/mysql_v1alpha1_mysqlcluster.yaml
config/samples/nfs_rc.yaml
config/samples/nfs_server.yaml
config/samples/pv-claim.yml
config/samples/pv-volume.yaml
docs/deploy_backup_restore_nfs.md
docs/en-us/deploy_backup_restore_s3.md
mysqlcluster/container/backup.go
mysqlcluster/container/init_sidecar.go
mysqlcluster/mysqlcluster.go
mysqlcluster/syncer/follower_service.go
mysqlcluster/syncer/leader_service.go
sidecar/config.go
sidecar/init.go
sidecar/server.go
sidecar/takebackup.go
utils/common.go
utils/constants.go

/enhancement
Fixes #148 
Summary:
1. create nfs resouce and nfs service
2. support backup to nfs and restore from nfs

*: support backup/restore with  NFS #148

---

charts/mysql-operator/templates/nfs_backup.yaml
charts/mysql-operator/values.yaml

/enhancement
Fixes #148
Summary:

chart: support NFS backup.

---

.github/workflows/build_sidecar_image.yml

/bug
Fixes #460
This instruction has more` --build-arg`, but runs successfully in CI, which causes the image that are produced and does not use `--build-arg`.
```
/usr/bin/docker buildx build --build-arg --build-arg XTRABACKUP_PKG=percona-xtrabackup-80 --file Dockerfile.sidecar --iidfile /tmp/docker-build-push-WFnJFw/iidfile
backup container: 
$ xtrabackup -v
xtrabackup version 2.4.24 based on MySQL server 5.7.35 Linux (x86_64) (revision id: b4ee263)
```
Summary:

ci: Fix `build-arg` not take effect.

---

.github/workflows/build_sidecar_image.yml

/bug
Fixes #
Summary:
IF does not take effect. syntax error

ci: fix syntax error in sidecar ci.

---

api/v1alpha1/mysqlcluster_webhook.go

/bug
Fixes #477
Summary:
Use webhook to forbidden the mysqlconf's modifies

*: Lowcase table name forbid to modify in my.cnf

---

README.md

/doc
Fixes #496
Summary: Update the README files and translate them into English.

Modify the English README file. #496

---

api/v1alpha1/backup_types.go
backup/syncer/job.go
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
mysqlcluster/syncer/role.go
sidecar/config.go
sidecar/server.go
sidecar/takebackup.go
utils/common.go
utils/constants.go

/enhancement
Fixes #453
Summary:
Add BackupName in `backup.Status`

*: Add backup Name  into Backup status

---

controllers/mysqlcluster_controller.go
controllers/status_controller.go
mysqlcluster/syncer/statefulset.go
mysqlcluster/syncer/status.go

/cleanup
1. status.go: adjust the log level(ERROR->DEBUG)
2. statefulset.go: remove unnecessary output items
fix: #508
Summary:

syncer: Reduce useless log output #508

---

charts/mysql-operator/templates/deployment.yaml

/bug
Fixes #511
Operator mount the host's time zone.

chart: Operator mount the host's time zone. #511

---

.gitignore
api/v1alpha1/mysqlcluster_types.go
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
docs/zh-cn/how_to_use_tls.md
mysqlcluster/container/init_sidecar.go
mysqlcluster/container/mysql.go
mysqlcluster/mysqlcluster.go
mysqlcluster/syncer/mysql_cm.go
mysqlcluster/syncer/mysql_configs.go
sidecar/init.go
utils/constants.go

Fixes #492
Summary:
Support tls for external

*: Support tls for external #492

---

mysqlcluster/mysqlcluster.go
mysqlcluster/syncer/mysql_configs.go

/enhancement
Fixes #501 
Summary:
1. When the redo log file size is not set manually, auto set  redo log file size is  25% of innodb_buffer_pool_size , but never over 8G.
2. when users want set over 8G,  they should set it in yaml file manually.

mysqlcluster: innodb_log_file_size auto config. #501

---

mysqlcluster/syncer/statefulset.go

/bug
/enhancement
Fixes #502 #310
Summary:
- bug fix: Update too many pods at the same time.
After deleting the pod, wait for the pod to restart.
- improvement: Optimize the logic of updatepod().
Use updatedReplicas and Spec.replicas to judge if the updatepod() is needed.
- improvement: switch leader to updated pod.

syncer: Optimize the logic of updating pod.

---

api/v1alpha1/mysqlcluster_types.go
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
config/samples/mysql_v1alpha1_mysqlcluster.yaml
config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml

MySQL8 does not support Tokudb, the `initTokuDB` should be set to false by default.
Fixes #555 
Summary:

api: Disable TOKUDB by default.

---

api/v1alpha1/mysqlcluster_types.go
build/xenon/Dockerfile
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
cmd/xenon/main.go
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
go.mod
go.sum
mysqlcluster/container/xenon.go
mysqlcluster/container/xenon_test.go
sidecar/config.go
utils/constants.go

/bug
/cleanup
/enhancement
Fixes #
Summary:

*: remove useless import and clear logic of xenonchecker.

---

api/v1alpha1/mysqluser_types.go
charts/mysql-operator/crds/mysql.radondb.com_mysqlusers.yaml
config/crd/bases/mysql.radondb.com_mysqlusers.yaml
config/samples/mysql_v1alpha1_mysqluser.yaml
controllers/mysqluser_controller.go
internal/sql_runner.go

/bug
/enhancement
Fixes #573 #577
Summary:
- add options `WithGrantOption`
- add options `TLSOptions`
- support create user with grant
- support create user with ssl options
- add print columns
```
» kubectl get mysqluser                                                                                                  
NAME          USERNAME      SUPERUSER   HOSTS   TLSTYPE   CLUSTER   NAMESPACE   AVAILABLE
normal-user   normal_user   false       ["%"]   NONE      sample    default     True
super-user    super_user    true        ["%"]   NONE      sample    default     True
» kubectl get mysqluser -o wide                                                                                         
NAME          USERNAME      SUPERUSER   HOSTS   TLSTYPE   CLUSTER   NAMESPACE   AVAILABLE …
```

*: Support to configure grant option and SSL when creating users.

---

.github/workflows/build_xenon_image.yml
.github/workflows/code_check.yml
.github/workflows/publish_images.yml

/enhancement
Fixes #
Summary:
- add codecheck items:
- make generate
- go vet
- make build
- add support for build xenon.

ci: update the codecheck items and the build items.

---

config/rbac/role.yaml
controllers/mysqlcluster_controller.go

/bug
Fixes #
Summary:
fix the bug 
```
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
2022-07-25T02:25:07.262Z        ERROR   controller-runtime.manager.controller.mysqlcluster      Reconciler error{"reconciler group": "mysql.radondb.com", "reconciler kind": "MysqlCluster", "name": "sample", "namespace": "default", "error": "roles.rbac.authorization.k8s.io \"sample\" is forbidden: user \"system:serviceaccount:default:controller-manager\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:default\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"pods/exec\"], Verbs:[\"create\"]}"} …
```

config,controllers: fix the bug of fail to create role

---

.github/workflows/publish_charts.yml
.github/workflows/publish_images.yml
.github/workflows/publish_release.yml
.github/workflows/release_drafter.yml

/enhancement
Fixes #616
Summary:
- add more assets in release 
- sample of the mysqluser
- package of the operator chart
- use the relative path
- build xenon when publish release
https://github.com/runkecheng/radondb-mysql-kubernetes/releases/tag/untagged-0ae7969c3d9c5f785fc2

ci: add more assets in release 

---

backup/cronbackup.go
controllers/backupcron_controller.go

/bug
Fixes #661
Summary:
1. when cluster is deleted, remove cronjob
2. when replica is zeror , remove cronjob
3. when backupschedule is set to empty, remove cronjob.

controllers: fix the bug cronjob exits when cluster is gone #661

---

charts/mysql-operator/charts/mysql-cluster/.helmignore
charts/mysql-operator/charts/mysql-cluster/Chart.yaml
charts/mysql-operator/charts/mysql-cluster/templates/NOTES.txt
charts/mysql-operator/charts/mysql-cluster/templates/_helpers.tpl
charts/mysql-operator/charts/mysql-cluster/templates/cert.tpl
charts/mysql-operator/charts/mysql-cluster/templates/mysqlcluster.yaml
charts/mysql-operator/charts/mysql-cluster/templates/mysqluser.yaml
charts/mysql-operator/charts/mysql-cluster/templates/tls_secrets.yaml
charts/mysql-operator/charts/mysql-cluster/values.yaml
charts/mysql-operator/templates/NOTES.txt
charts/mysql-operator/values.yaml

/enhancement
Fixes #516
Summary:
add a subchart `mysqlcluster`
uses:
```
helm install demo charts/mysql-operator --set manager.tag=v2.2.0-beta.1 --set mysqlcluster.install=true --set mysqlcluster.operatorVersion=v2.2.0-beta.1
```
next:

chart: Support the use of Helm to install MySQL cluster

---

api/v1alpha1/mysqlcluster_webhook.go

/bug
Fixes #667
Summary:
1. add webhook, when nfsserverAddress is not set to ip, report error.
2. if backup schedule is set but no backupSecretName or nfsServerAdress, report error.

api: add webhook for nfs backup #667

---

api/v1alpha1/backup_types.go
backup/syncer/job.go
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
controllers/backup_controller.go

/bug
Fixes #687 
Summary:
1. change the order for backup and backupStatus
2. get rid off the omitempty

*: fix the bug status always empty till backup complete #687

---

api/v1alpha1/mysqlcluster_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
charts/mysql-operator/templates/mysql57_template.yaml
charts/mysql-operator/templates/mysql80_template.yaml
charts/mysql-operator/values.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
controllers/mysqlcluster_controller.go
mysqlcluster/mysqlcluster.go
mysqlcluster/syncer/mysql_cm.go
mysqlcluster/syncer/objectSyncer.go
mysqlcluster/syncer/statefulset.go
sidecar/config.go
sidecar/init.go

/enhancement
ref #580
Summary:
1. add an option for the objectSyncer: forceSync; if false, objectSyncer will not force synchronous resources, it will only create resources without existence.
2. support MySQL configuration template
3. generate MySQL config template by default
4. support customized initsql
```
❯ kubectl get cm sample-mysql -oyaml
apiVersion: v1
data:
init.sql: CREATE DATABASE IF NOT EXISTS testinit;
...
bash-4.4$ cat /etc/mysql/conf.d/init.sql 
SET @@SESSION.SQL_LOG_BIN=0;
CREATE DATABASE IF NOT EXISTS radondb;
...
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS testinit;
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| radondb            |
| sys …
```

*: support MySQL configuration template

---

test/e2e/chaos/podChaos.go
test/e2e/e2e_test.go
test/e2e/framework/chaos.go
test/e2e/framework/cleanup.go
test/e2e/framework/framework.go
test/e2e/framework/mysqlcluster.go

/enhancement
Fixes #682 
Summary:
Chaos Mesh is a cloud native Chaos Engineering platform that orchestrates chaos on Kubernetes [`Chaos documents.`](https://chaos-mesh.org/zh/docs/).Chaos mesh use CRD defnine many types of fault and provide detailed of parameter description.So wei can mainly focus on life cycle of CRD instead of focus on basic implements of specific faults.
The details of this implements as follows:
- introduce chaos mesh api into e2e
- programming API according to definition of faults
- programming test case
apis:

feat(e2e): add podchaos api and test cases

---

mysqlcluster/syncer/statefulset.go

/bug
Fixes #531
Summary:
1. when set images error, it cannot make statefuset work correct until 2 hours timeout.
2. You could set replica 0, then set image to correct.

mysqlcluster: when image set error, use replica 0 to rescure it #531

---

api/v1alpha1/mysqlcluster_webhook.go
backup/syncer/job.go
config/samples/nfs_server.yaml
mysqlcluster/mysqlcluster.go
utils/common.go

/enhancement
Fixes #716 
Summary:
1. take the nfsadress as `ip` and `path`, split with `:`

*: support the x.x.x.x:/dbbackup nfs address. #716

---

Makefile
backup/syncer/job.go
charts/mysql-operator/Chart.yaml
charts/mysql-operator/templates/deployment.yaml
charts/mysql-operator/values.yaml
controllers/backup_controller.go
controllers/status_controller.go
mysqlcluster/container/auditlog_test.go
mysqlcluster/container/container.go
mysqlcluster/container/init_mysql_test.go
mysqlcluster/container/init_sidecar_test.go
mysqlcluster/container/metrics_test.go
mysqlcluster/container/slowlog_test.go
mysqlcluster/container/xenon_test.go
mysqlcluster/mysqlcluster.go
mysqlcluster/mysqlcluster_test.go

/enhancement
Fixes #718 
Summary:
```shell
helm get values  mysql-operator -a|grep  ^image
imageNamespaceOverride: qq
imagePrefix: z.com
imagePullPolicy: IfNotPresent
kubectl get deployments.apps mysql-operator -o yaml|grep -E 'IMAGE_NAMESPACE_OVERRIDE|IMAGE_PREFIX|image'
image: z.com/qq/kube-rbac-proxy:v0.8.0
imagePullPolicy: IfNotPresent
- name: IMAGE_NAMESPACE_OVERRIDE
- name: IMAGE_PREFIX
image: z.com/qq/mysql-operator:latest
imagePullPolicy: IfNotPresent
kubectl describe  po sample-mysql-2|grep image
Normal  Pulled     14m   kubelet            Container image "z.com/qq/mysql57-sidecar" already present on machine
Normal  Pulled     14m   kubelet            Container image "z.com/qq/percona-server:5.7.34" already present on machine
Normal  Pulled     14m   kubelet            Container …
```

container: support image namespace override

---

api/v1alpha1/mysqlcluster_webhook.go
config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml

/bug
Fixes #722 
Summary:
add webhook and check the configmap of template exist.

api: add mysqltemplate webhook check #722

---

api/v1alpha1/mysqlcluster_webhook.go

/enhancement
Fixes #727 #726 
Summary:
```shell
kubectl edit mysql sample 
error: mysqlclusters.mysql.radondb.com "sample" could not be patched: admission webhook "vmysqlcluster.kb.io" denied the request: forbidden: spec.MysqlVersion is 5.7, but spec.PodPolicy.SidecarImage is not 5.7
You can run `kubectl replace -f /tmp/kubectl-edit-3934028760.yaml` to try this update again.
```

api: Add webhook check for sidecar image

---

Makefile
api/v1alpha1/backup_types.go
api/v1alpha1/mysqlcluster_types.go
charts/mysql-operator/Chart.yaml
charts/mysql-operator/charts/mysql-cluster/Chart.yaml
charts/mysql-operator/charts/mysql-cluster/values.yaml
charts/mysql-operator/crds/mysql.radondb.com_backups.yaml
charts/mysql-operator/crds/mysql.radondb.com_mysqlclusters.yaml
charts/mysql-operator/values.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
config/manager/kustomization.yaml
config/samples/mysql_v1alpha1_backup.yaml
config/samples/mysql_v1alpha1_mysqlcluster.yaml
config/samples/mysql_v1alpha1_mysqlcluster_backup_schedule_demo.yaml
config/samples/mysql_v1alpha1_mysqlcluster_mysql8.yaml
config/samples/mysql_v1alpha1_mysqlcluster_podAntiAffinity.yaml
test/e2e/framework/mysqlcluster.go
test/e2e/framework/test_context.go

*: update version to 2.3.0

---

Dockerfile
api/v1alpha1/mysqluser_types.go
charts/mysql-operator/crds/mysql.radondb.com_mysqlusers.yaml
config/crd/bases/mysql.radondb.com_mysqlusers.yaml
controllers/mysqluser_controller.go
internal/sql_runner.go
utils/unsafe.go
utils/unsafe_test.go

*: fix user create issue

---

cmd/manager/main.go
go.mod
go.sum

/enhancement
Fixes #
add ubuer log format
Summary:
add uber log format.

cmd: add uber log fmt

---

Makefile
api/v1alpha1/backup_types.go
api/v1alpha1/mysqlcluster_types.go
api/v1beta1/mysqlcluster_types.go
charts/mysql-operator/Chart.yaml
charts/mysql-operator/charts/mysql-cluster/Chart.yaml
charts/mysql-operator/charts/mysql-cluster/values.yaml
charts/mysql-operator/templates/mysql.radondb.com_backups.yaml
charts/mysql-operator/templates/mysql.radondb.com_mysqlclusters.yaml
charts/mysql-operator/values.yaml
config/crd/bases/mysql.radondb.com_backups.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
config/manager/kustomization.yaml
test/e2e/framework/mysqlcluster.go
test/e2e/framework/test_context.go

/enhancement
Fixes #
1. modify the version.
Summary:

chart,config: modify the 3.0.0-alpha to 3.0.0

---

api/v1alpha1/mysqlcluster_types.go
api/v1alpha1/zz_generated.deepcopy.go
api/v1beta1/mysqlcluster_types.go
api/v1beta1/zz_generated.conversion.go
api/v1beta1/zz_generated.deepcopy.go
charts/mysql-operator/templates/mysql.radondb.com_mysqlclusters.yaml
config/crd/bases/mysql.radondb.com_mysqlclusters.yaml
config/samples/mysql_v1beta1_backup.yaml
config/samples/mysql_v1beta1_mysqlcluster.yaml
internal/sql_runner.go
mysqlcluster/syncer/readonly_statefulset.go
mysqlcluster/syncer/status.go

/enhancement
Fixes # add replica lag parameters
Summary:

*: add replica lag parameter

---

mysqlcluster/syncer/readonly_statefulset.go
mysqlcluster/syncer/status.go

*: fix the change master bug

---

cmd/xenon/main.go
internal/pod_executor.go
mysqlcluster/syncer/status.go
utils/constants.go

/enhancement
Fixes # add tryleader command 
Summary:
use label to add tryleader command

*: try leader by label

---

Dockerfile.mysql80arm64
Dockerfile57.sidecar
Dockerfile80.sidecar
build_mutiplatform.sh
mysqlcluster/syncer/mysql_cm.go

/enhancement
Fixes # do all for arm64 mysql
Summary:

*. delete audit_log in arm64, and build mysql's arm64 dockerfile

---

charts/mysql-operator/templates/cluster_rbac.yaml
cmd/manager/main.go
config/rbac/role.yaml
config/samples/mysql_v1beta1_mysqlcluster.yaml
controllers/mysqlcluster_controller.go
utils/incluster.go

/enhancement
解决DMP重装时候，CRD 证书不对的问题，在operator 运行前8分钟，检测并校验crd 的证书
Fixes #
Summary:

add the crd update for DMP reinstall

---

sidecar/config.go

sidecar: fix the bug of start index of serverid

---

mysqlcluster/syncer/readonly_statefulset.go

/bug
Fixes #
1. The leader or followers' replications are started by xenons, so the mysqlchecker can work well.
2. However, the ReadOnly pod do not have xenon container, which make it is unhealthy which is checked by mysqlchecker.
3. The unhealthy pod lead to unready of Readonly statefulset, reasulting in operator cannot go on reconciling. 
Summary:

fix the RO readness check
